import Foundation
import RealCore
import RealMaterials
import RealLibrary

/// Regenerates CATALOG.md from the registries. CI fails when the committed file is stale.
func catalogCommand() throws {
    let root = try repoRoot()
    var md = "# Catalog\n\nGenerated by `swift run -q realityhd catalog`. Do not edit by hand.\n"
    let kinds: [(String, [any RealAsset.Type])] = [("Nature", Nature.all), ("Props", Props.all), ("Structures", Structures.all)]
    for (title, types) in kinds {
        md += "\n## \(title)\n\n"
        guard !types.isEmpty else { md += "None yet. See [docs/IDEAS.md](docs/IDEAS.md).\n"; continue }
        md += "| id | tags | LOD tris | budget | materials | author | summary |\n|---|---|---|---|---|---|---|\n"
        for t in types {
            let m = t.init().build(seed: 1)
            let tris = m.levels.map { "\($0.triangleCount)" }.joined(separator: " / ")
            let mats = m.levels[0].materials.map { "`\($0)`" }.joined(separator: " ")
            md += "| [`\(t.id)`](docs/assets/\(t.id).png) | \(t.tags.joined(separator: ", ")) | \(tris) | \(t.budget) | \(mats) | \(t.author) | \(t.summary) |\n"
        }
    }
    md += "\n## Articulated\n\nLive with `RealityHD.articulated(id)` or `scene.addLive`; bake one state with `build(seed:state:)`. `realityhd states <id>` renders every state.\n\n"
    md += "| id | states | joints | LOD0 tris (min-max over states) |\n|---|---|---|---|\n"
    for t in Catalog.articulated {
        let rig = t.init().rig(seed: 1)
        let joints = rig.parts.filter { $0.joint.kind != .fixed && $0.joint.mimic == nil }.map { p -> String in
            let unit = p.joint.kind == .revolute ? "°" : " m"
            return "`\(p.name)` \(fmtRange(p.joint.range))\(unit)"
        }
        let tris = rig.stateNames.map { rig.posed($0).levels[0].triangleCount }
        md += "| [`\(t.id)`](docs/assets/\(t.id).png) | \(rig.stateNames.joined(separator: ", ")) | \(joints.joined(separator: ", ")) | \(tris.min() ?? 0)-\(tris.max() ?? 0) |\n"
    }
    md += "\n## Scenes\n\n| id | tags | author | summary |\n|---|---|---|---|\n"
    for s in SceneCatalog.all {
        md += "| [`\(s.id)`](docs/scenes/\(s.id).png) | \(s.tags.joined(separator: ", ")) | \(s.author) | \(s.summary) |\n"
    }
    md += "\n## Materials\n\nKeys accept a hex tint suffix, e.g. `metal.painted:1F4E8C`.\n\n"
    md += "| key | program | tile (m) | res | mode | wind | extras |\n|---|---|---|---|---|---|---|\n"
    for s in MaterialLibrary.all {
        var extras: [String] = []
        if s.translucency > 0 { extras.append("translucency") }
        if s.antiTile { extras.append("anti-tile") }
        if s.triplanar { extras.append("triplanar") }
        if s.topAmount > 0 { extras.append("moss layer") }
        if s.hasMetallicMap { extras.append("metallic map") }
        let tile = s.tileSize > 0 ? String(format: "%.2g", s.tileSize) : "atlas"
        let wind = s.wind > 0 ? String(format: "%.2g", s.wind) : "-"
        md += "| `\(s.key)` | \(s.program.map { "\($0)" } ?? "scalar") | \(tile) | \(s.program == nil ? "-" : "\(s.resolution)") | \(s.mode) | \(wind) | \(extras.joined(separator: ", ")) |\n"
    }
    md += "\n## Texture programs\n\n" + TextureProgram.allCases.map { "`\($0)`" }.joined(separator: " ") + "\n"
    try md.write(to: root.appendingPathComponent("CATALOG.md"), atomically: true, encoding: .utf8)
    print("CATALOG.md")
}

func fmtRange(_ r: ClosedRange<Float>) -> String {
    func f(_ v: Float) -> String { v == v.rounded() ? String(Int(v)) : String(format: "%.2g", v) }
    return "\(f(r.lowerBound))...\(f(r.upperBound))"
}
