/// Trees, rocks, ground and grass. New nature assets go in a subfolder here and are listed below.
public enum Nature {
    public static let all: [any RealAsset.Type] = [
        OakTree.self, BirchTree.self, SpruceTree.self, Shrub.self, Tree.self,
        Boulder.self, Pebbles.self, GroundPatch.self, GrassClump.self,
        GrassTuft.self,
        TallGrass.self,
        DryGrass.self,
        LawnPatch.self,
        Fern.self,
        MeadowFlowers.self,
        CloverPatch.self,
        Dandelion.self,
        ReedClump.self,
        MushroomCluster.self,
        MossMound.self,
        IvyPatch.self,
        LeafLitter.self,
        MapleTree.self, BeechTree.self, WillowTree.self, JapaneseMaple.self, DeadSnag.self, AspenTree.self,
        TerrainHill.self, DirtPath.self, Puddle.self, MudPatch.self, GravelPatch.self, SnowDrift.self, SandDune.self,
        ScotsPine.self,
        FirTree.self,
        CypressTree.self,
        SnowySpruce.self,
        PalmTree.self,
        Saguaro.self,
        BarrelCactus.self,
        Agave.self,
        LarchTree.self,
        RockOutcrop.self, CliffFace.self, ScreePile.self, RiverStones.self, SteppingStone.self, MossyRock.self,
        MesaRock.self, Flagstone.self, RockPile.self,
        LogStump.self,
        Firewood.self,
        FallenLog.self,
        RootStump.self,
        Ladybug.self,
        // realityhd:nature
    ]
}
