/// Movable objects under ~3 m: furniture, containers, street furniture, tools. Each prop is one file
/// in a theme subfolder (Containers/, Furniture/, Industrial/, Street/, ...) and is listed below.
public enum Props {
    public static let all: [any RealAsset.Type] = [
        WoodenCrate.self, Barrel.self, OilDrum.self, ParkBench.self, PicnicTable.self, StreetLamp.self,
        TrafficCone.self, FireHydrant.self, Bollard.self, Pallet.self, Mailbox.self, TrashCan.self,
        Sawhorse.self,
        Wheelbarrow.self,
        CementMixer.self,
        RebarBundle.self,
        Sandbag.self,
        CableSpool.self,
        TrafficBarrel.self,
        Dumpster.self,
        RoundHayBale.self,
        SquareHayBale.self,
        WaterTrough.self,
        MilkCan.self,
        FeedSack.self,
        TractorTire.self,
        FirewoodStack.self,
        CampfireRing.self,
        DomeTent.self,
        CampChair.self,
        Cooler.self,
        CampLantern.self,
        Canoe.self,
        AxeInStump.self,
        VintageSuitcase.self,
        ChesterfieldArmchair.self,
        BentwoodChair.self,
        AnglepoiseLamp.self,
        CopperKettle.self,
        StonewareCrock.self,
        StoneLantern.self,
        ShipAnchor.self,
        ToolChest.self,
        WickerBasket.self,
        FilingCabinet.self,
        OfficeChair.self,
        DeskPedestal.self,
        StorageCabinet.self,
        ExecutiveDesk.self,
        PedalBin.self,
        Laptop.self,
        HardcoverBook.self,
        DesktopMonitor.self,
        BankerLamp.self,
        CeilingLight.self,
        KeyboardMouse.self,
        CoffeeMug.self,
        PaperStack.self,
        OfficeDesk.self,
        Bookshelf.self,
        ConferenceTable.self,
        LobbySofa.self,
        ReceptionDesk.self,
        Whiteboard.self,
        WaterCooler.self,
        SnakePlant.self,
        HomePlate.self,
        BaseBag.self,
        BaseballBat.self,
        Baseball.self,
        BattingHelmet.self,
        BallBucket.self,
        DoctorStool.self,
        OverbedTable.self,
        // realityhd:prop
    ]
}
